version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "q1w2e3r4@"
      MYSQL_DATABASE: "spring_course_db"
    ports:
      - "3306:3306"
    volumes:
      - /home/felipe/workspace/docker/mysql/volume:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 9000:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge